inventory:
    plugin: SimpleInventory
    options:
        host_file: "inventory/topo2/hosts.yaml"
        group_file: "inventory/topo2/groups.yaml"
        defaults_file: "inventory/topo2/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100